apiVersion: v1
kind: Service
metadata:
  name: student-management-service
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
  - port: 80
    targetPort: 8089
    nodePort: 30080
